# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Warpcon 200"
email: "warpcondirector@gmail.com"
description: "Warpcon 34 is the 34th annual gaming convention in UCC"
# baseurl: "https://gregorioustechorious.github.io/warpcon.ie/"
baseurl: "https://www.warpcon.ie"
url: "https://www.warpcon.ie"
# url: "https://gregorioustechorious.github.io/warpcon.ie/"
permalink: "/games/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Warpcon"
organizerAlternateName: "Warpcon, an initiative by UCC Warps"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "warpcondirector@gmail.com"
organizerLogo: "/img/seo/logos.png"
organizerLink: "https://facebook.com/WARPCON"

# Head
metaKeywords: "convention, ttrpgs, ccgs, wargames, ucc, cork, dnd, cyberpunk, magic the gathering"
twitterAccount: "@warpcon"
socialImageSrcGooglePlus: "/img/seo/logos.png"
socialImageSrcTwitter: "/img/seo/logos.png"
socialImageSrcFacebook: "/img/seo/logos.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/games/", text: "Games"}
  - {permalink: "/schedule", text: "Schedule"}
#  - {permalink: "/speakers/", text: "Speakers"}
#  - {permalink: "/team/", text: "Team"}
#  - {permalink: "/logistics/", text: "Logistics"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSds7_XGjjyr1WuwuL3QSxhhg1R97B132o_IrN-EuleW2JrMsA/viewform?usp=sf_link", text: "Become a trader"}
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a vendor"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSds7_XGjjyr1WuwuL3QSxhhg1R97B132o_IrN-EuleW2JrMsA/viewform?usp=sf_link", text: "Become a trader"}
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a vendor"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Warpcon 200"
eventDate: "January 26th-28th, 2024"
typeoutTextValues: '"", "TTRPGs", "CCGs", "Wargames", "UCC", "Cork"'
typeoutFallback: ""
heroButtons:
# - {link: "/assets/mainhandbook.pdf", text: "Handbook"}
 - {permalink: "/#tickets", text: "Tickets"}
#  - {link: "/#staff", text: "Staff Application"}
#  - {link: "#", text: "Staff application", disabled: true}
#  - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdW3TUd-WJG05cU-E4ebJN2YebRrKga6oix7W74uRJx01YAXQ/viewform?usp=sf_link", text: "Trader application"}
#  - {link: "#", text: "Vendor application", disabled: true}

# About Block
aboutTitle: "About Warpcon"
aboutBlock:
 - {title: "TTRPGs",          image: "ttrpgs.jpg",      text: "D&D, Cyberpunk, Homebrew and many other TTRPGs on Friday, Saturday and Sunday."}
 - {title: "CCGs",            image: "ccgs.jpg",        text: "Magic the Gathering, Pokémon, Yu-Gi-Oh and Lorcana events and tournaments will be hosted by Sandbox"}
 - {title: "LARPs",           image: "larps.jpg",       text: "All weekend, we will be hosting organized LARPs events."}
 - {title: "Wargames",        image: "wargames.jpg",    text: "On Saturday and Sunday, we will be hosting <a href='/assets/40k-2024.pdf'>Warhammer 40k</a> and <a href='/assets/BleedBowl-2024.pdf'>Bloodbowl</a>. As well as LOTR and smaller tournaments"}
 - {title: "Boardgames",      image: "boardgames.jpg",  text: "Many boardgames will be available for attendees to play at any time during the convention."}
 - {title: "Charity",         image: "charity.jpg",     text: "On Saturday night, we will be holding a charity auction in the New Bar, with proceeds going to Cork Children's hospital"}
# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "gamers", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of fun games and networking"}
#  - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "12", specialCharacter: "", info: "rooms booked", detail: "packed full of games"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
# rockstarSpeakersImage: "rockstar-speakers.jpg"
# rockstarSpeakersCount: 4
# rockstarSpeakersTitle: "Rockstar speakers"
# rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Devere Hall"
eventLocationLink: "https://warpcon.eventbrite.com"
eventStreetAddress: "College Road"
eventAddressLocality: "Cork City"
eventAddressLocalityRegion: "Cork"
eventPostalCode: "79000"
eventAddressCountry: "Ireland"
eventStartTime: "2023-01-27T17:00"
eventDoorTime: "17:00"
eventEndTime: "2023-01-29T23:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "stud_centre.jpg"
venueSmallImage1: "dev_hall.jpg"
venueSmallImage2: "newbar.jpg"
venueSmallImage3: "orb.jpg"
venueTitle: "UCC Campus"
venueFeatures: ["12 rooms", "<b>Devere Hall</b> - Reception & Trader Hall", "Located upstairs in Student Centre"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "warpcon"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets can also be purchased at the reception desk on the day. For college society group bookings, please contact us at <a href='mailto:warpcondirector@gmail.com'>warpcondirector@gmail.com</a>."
ticketsOffers:
 -
  name: "CCGs Pass"
  price: "€10"
  ribbon: "Optional"
  priceCurrency: "EUR"
  ticketsNumber: ""
  buyButtonLink: "https://uccsocieties.ticketsolve.com/ticketbooth/shows/1173651839"
  buyButtonText: "Buy now!"
  ticketContentList: ["Access to CCGs rooms and special events", "Access to Pokemon, Lorcana, Yu-Gi-Oh and MTG games"]
  # validFrom: "2014-08-25T10:00"
  # validThrough: "2014-09-30T23:59"
 -
  name: "General Admission"
  price: "€25"
  priceCurrency: "EUR"
  ticketsNumber: ""
  featured: true
  buyButtonLink: "https://uccsocieties.ticketsolve.com/ticketbooth/shows/1173651839"
  buyButtonText: "Buy now!"
  ticketContentList: ["Admission to Warpcon convention","Access to CCG Tournaments", "Access to all boardgames and TTRPGs"]
  # validFrom: "2014-10-01T00:00"
  # validThrough: "2014-10-23T23:59"
  # disabled: true
 -
  name: "Wargames Pass"
  price: "10"
  ribbon: "Optional"
  priceCurrency: "EUR"
 # buyButtonLink: "https://uccsocieties.ticketsolve.com/ticketbooth/shows/1173651839"
  buyButtonText: "Buy now!"
  # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Access to Wargames rooms", "Access to Warhammer. For Bloodbowl tickets please see rulepack above*"]

# Footer
socialLinks:
 - {link: "https://facebook.com/WARPCON",   icon: "facebook"}
 - {link: "https://instagram.com/WARPCON",  icon: "instagram"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
    - {link: "https://warpcon.eventbrite.ie",       text: "Eventbrite"}
    - {link: "https://www.facebook.com/WARPCON/",   text: "Facebook"}
    - {link: "https://www.instagram.com/WARPCON/",  text: "Instagram"}

 -
  title: "Contacts"
  links:
   - {link: "mailto:warpcondirector@gmail.com",   text: "warpcondirector@gmail.com"}
   - {link: "mailto:warpcontrader@gmail.com",     text: "warpcontrader@gmail.com"}
   - {link: "mailto:warpconsecretary@gmail.com",  text: "warpconsecretary@gmail.com"}
   - {link: "mailto:warpconstaff@gmail.com",      text: "warpconstaff@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: ""

# Speakers List Block
showSessions: false
